$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train model
version: 10
type: command
inputs:
  input_data: 
    type: uri_file
outputs:
  output_data:
    type: uri_file
code: ./src
environment: 'azureml:titanic-data-env:4.0'
  # image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest


command: python train.py --input_data ${{inputs.input_data}} --output_data ${{outputs.output_data}}

